### ISSUE TITLE
oxford command seems to be broken.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#13]
My and others' rbots' oxford command seems to be broken:
...
[11:30pm] <AntDude> !version
11:30PM <testrbot> I'm a v. 0.9.15 (journal branch, revision e358601 [fixes registry for 2.3.0,
          bug caused by wrong #get_impl]) [6 months, 15 days, 14 hours, 17 minutes and 27
          seconds ago] rubybot, (c) Giuseppe Bilotta and the rbot development team -
          http://ruby-rbot.org
[11:30pm] <AntDude> ah
[11:31pm] <AntDude> !oxford test
11:31PM <testrbot> test not found
...

Thank you in advance. :)

**Comment by antdude** [comment]
Thank you for fixing this. It worked in one of my upgraded rbots (Bender, Flexo is still running his manual "find ~/.rbot/registry_tc -iname '*.tdb' | xargs -n1 tcbmgr optimize" command).

**Comment by antdude** [comment]
Hmm. My Flexo on my 12 years old Debian Jessie v8 box still doesn't work:
[12:54pm] Ant> flexo help failed plugins
12:54PM Flexo> oxford.rb in /home/ant/bin/rbot/data/rbot/plugins failed with error SyntaxError:
          oxford.rb:52: syntax error, unexpected ':', expecting =>
12:54PM Flexo> ..., headers: {'X-Requested-With': 'XMLHttpRequest'})
12:54PM Flexo> ...                               ^
12:54PM Flexo> oxford.rb:52: syntax error, unexpected '}', expecting keyword_end...
[12:55pm] <Ant> grrrrrrrrrrrrrr
[12:56pm] <Ant> flexo version
12:56PM <Flexo> Ant: I'm a v. 0.9.15 (master branch, revision 2a084cf [plugin(oxford): fix empty
          service result see #37], 3 files changed) [1 hour and 17 seconds ago] rubybot, (c)
          Giuseppe Bilotta and the rbot development team - https://ruby-rbot.org
$ ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
...
Updating installed gems
Updating activesupport
ERROR:  Error installing activesupport:
        zeitwerk requires Ruby version >= 2.4.4.
Updating bigdecimal
ERROR:  Error installing bigdecimal:
        bigdecimal requires Ruby version >= 2.4.0.
Updating bundler
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.
Updating faraday
ERROR:  Error installing faraday:
        faraday requires Ruby version >= 2.3.
Updating gettext
ERROR:  Error installing gettext:
        gettext requires Ruby version >= 2.5.0.
Updating i18n
ERROR:  Error installing i18n:
        i18n requires Ruby version >= 2.3.0.
Updating io-console
ERROR:  Error installing io-console:
        io-console requires Ruby version >= 2.4.0.
Updating minitest
ERROR:  Error installing minitest:
        minitest requires Ruby version ~> 2.2.
Updating nokogiri
ERROR:  Error installing nokogiri:
        nokogiri requires Ruby version >= 2.3.0.
Updating psych
ERROR:  Error installing psych:
        psych requires Ruby version >= 2.2.2.
Updating rack
ERROR:  Error installing rack:
        rack requires Ruby version >= 2.3.0.
Updating rake
ERROR:  Error installing rake:
        rake requires Ruby version >= 2.2.
Updating rdoc
ERROR:  Error installing rdoc:
        rdoc requires Ruby version >= 2.4.0.
Updating sinatra
ERROR:  Error installing sinatra:
        rack requires Ruby version >= 2.3.0.
Gems updated: zeitwerk bigdecimal bundler faraday gettext i18n io-console minitest nokogiri psych rack rake rdoc rack
Cleaning up installed gems...
Clean Up Complete


Bender in Fedora v31 works fine with its ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]. Is it because of the very old Ruby version that is not working for my Flexo rbot?

**Comment by mattzque** [comment]
Yes ruby version is too old, its a newer ruby syntax I've started using (`{key: value}` instead of `{key => value}`).
Besides jessie no longer being maintained/ receiving security fixes, Ruby itself is also no longer receiving security updates.

I think I support versions `>= 2.5` going forward: https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions

**Comment by antdude** [comment]
OK and thanks. Yeah, my PC is 12 years old with very limited old hardware resources.  :(
