### ISSUE TITLE
My rbot's uptime.rb (gfax's 2014-02-25) doesn't work.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#17]
E, [2016/12/27 00:46:08#12498] ERROR -- plugins.rb:1078:in `rescue in privmsg': Plugin uptime privmsg() failed:
E, [2016/12/27 00:46:08#12498] ERROR --                                       : #<NoMethodError: undefined method `captures' for nil:NilClass>
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/.rbot/plugins/uptime.rb:16:in `last_reboot'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/messagemapper.rb:281:in `block in handle'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/messagemapper.rb:247:in `each'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/messagemapper.rb:247:in `handle'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:232:in `handle'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:269:in `privmsg'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:1075:in `privmsg'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:1102:in `irc_delegate'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/ircbot.rb:682:in `block in initialize'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/rfc2812.rb:1527:in `call'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/rfc2812.rb:1527:in `handle'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/rfc2812.rb:1422:in `process'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/ircbot.rb:1063:in `mainloop'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : /home/ant/bin/rbot/bin/rbot:120:in `<top (required)>'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : ./launch_here.rb:68:in `load'
E, [2016/12/27 00:46:08#12498] ERROR --                                       : ./launch_here.rb:68:in `<main>'

[12:48am] <Ant> @version
12:48AM <Flexo> Ant: I'm a v. 0.9.15 (master branch, revision e358601 [fixes registry for 2.3.0, bug caused
          by wrong #get_impl], 876 files changed) [9 months, 6 days, 16 hours, 37 minutes and 30 seconds
          ago] rubybot, (c) Giuseppe Bilotta and the rbot development team - http://ruby-rbot.org

Is there an updated version that works? Thank you in advance. :)

**Comment by antdude** [comment]
Weird. Now, it works:
[01:52pm] <Ant> @uptime
01:52PM <Flexo> Ant: Last reboot was on 2017-08-18 04:39:35 -0700.
[01:53pm] <Ant> +uptime
01:53PM <Bender> Ant: Last reboot was on 2017-08-02 22:59:07 -0700.

**Comment by jaythomas** [comment]
This is not an rbot plugin. That's something I wrote awhile back: https://github.com/gfax/rbot-plugins/blob/master/uptime.rb
