### ISSUE TITLE
rbot's stock command no longer works.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#22]
My ~/.rbot/rbot.log shows this:

E, [2017/09/11 13:08:17#21362] ERROR -- plugins.rb:1078:in `rescue in privmsg': Plugin stock privmsg() failed:
E, [2017/09/11 13:08:17#21362] ERROR --                                       : #<NoMethodError: undefined method `sub' for nil:NilClass>
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/.rbot/plugins/GoogleStocks-0.1.rb:41:in `stock'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/messagemapper.rb:281:in `block in handle'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/messagemapper.rb:247:in `each'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/messagemapper.rb:247:in `handle'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:232:in `handle'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:269:in `privmsg'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:1075:in `privmsg'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/plugins.rb:1102:in `irc_delegate'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/ircbot.rb:682:in `block in initialize'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/rfc2812.rb:1527:in `call'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/rfc2812.rb:1527:in `handle'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/rfc2812.rb:1422:in `process'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/lib/rbot/ircbot.rb:1063:in `mainloop'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : /home/ant/bin/rbot/bin/rbot:120:in `<top (required)>'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : ./launch_here.rb:68:in `load'
E, [2017/09/11 13:08:17#21362] ERROR --                                       : ./launch_here.rb:68:in `<main>'

It used to work a few weeks ago. Thank you in advance. :)

**Comment by mattzque** [comment]
not part of official rbot, should be fixed and included in rbot, can you send me the plugin file?

**Comment by antdude** [comment]
http://zimage.com/~ant/temp/imdb.rb for my copy. Please kindly let me know when you got it so I can delete it. :)

**Comment by mattzque** [comment]
@antdude I'm glad to see you still on here. thanks for the issues you opened, I should have a bit of time to work on them now.

The file you sent is the imdb plugin, I thought this was about a stock plugin, GoogleStocks?

**Comment by antdude** [comment]
Ooops!  http://zimage.com/~ant/temp/GoogleStocks-0.1.rb

I guess you don't need imdb.rb so I will nuke it from orbit. ;)

**Comment by mattzque** [comment]
I got it thank you

**Comment by antdude** [comment]
You're welcome. Let's get rbot to working. I noticed a lot of changes. I hope future releases will still work in my 12 years old 64-bit Debian Jessie v8 box.
