### ISSUE TITLE
Note command shouldn't be case sensitive.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#24]
Example: note rbot and note Rbot should be the same.

**Comment by mattzque** [comment]
I cannot reproduce this, I added a test case that shows that it works. The plugin is downcasting the nick name before saving it and when checking it against remembered notes.

**Comment by antdude** [comment]
I can't reproduce it anymore too:
[12:37pm] Ant> @note ant test
12:37PM Flexo> done, Ant
[12:37pm] Ant> t
12:37PM Flexo> Ant, you have notes! [Apr- 7 12:37] <Ant> test

I guess it was fixed or something over the years?
