### ISSUE TITLE
rbot's math command isn't accurate.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#26]
...
[02:18pm] Ant> flexo math 4.99*5
02:18PM Flexo> Ant: 24.950000000000003
03:04PM util> hrmm i wouldn't trust Flexo's math haha
[04:41pm] Ant> flexo gcalc 4.99*5
04:41PM Flexo> Ant: 4.99 * 5 = 24.95
[04:41pm] Ant> Why?
04:49PM util> 24.95 !=  24.950000000000003
[04:49pm] Ant> ah
[04:49pm] Ant> bender math 4.99*5
04:49PM Bender> Ant: 24.950000000000003
[04:49pm] Ant> heh
...

**Comment by Oblomov** [comment]
[Standard behavior for binary floating point numbers](https://floating-point-gui.de/).
