### ISSUE TITLE
Horoscope plugin does not work.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#3]
Hello.

Horo doesn't seem to work with any rbots except the official rbot which doesn't have it:
...
[12:34pm] <Ant> @horo set Capricorn
12:34PM <Flexo> okay then :), Ant
[12:34pm] <Ant> @horo dailyoverview
12:34PM <Flexo> Ant: error (sorry, snaky!) -> This is not well formed XML
12:34PM <Flexo> Missing end tag for 'meta' (got "head")
12:34PM <Flexo> Line: 80
12:34PM <Flexo> Position: 3622
12:34PM <Flexo> Last 80 unconsumed characters:
[12:34pm] <Ant> bah
[12:35pm] <Ant> @version
12:35PM <Flexo> Ant: I'm a v. 0.9.15 (master branch, revision 43ebe3a [script: make $SAFE configureable],
          4 files changed) [4 months, 14 days, 1 hour, 31 minutes and 45 seconds ago] rubybot, (c)
          Giuseppe Bilotta and the rbot development team - http://ruby-rbot.org
...
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]

Thank you in advance. :)

**Comment by ahpook** [comment]
@antdude where is this plugin from? i don't see it in the source tree.

**Comment by jaythomas** [comment]
That's a third-party plugin. This is not an rbot issue.
