### ISSUE TITLE
"imdb Belgravia" doesn't show anything.

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#44]
~/.rbot/rbot.log shows nothing about it from my two rbots (v. 0.9.15 (master branch, revision 40ba5f6
          [refactor: remove global bot instance, closes #42]) [21 minutes and 34 seconds ago] rubybot, (c) Giuseppe Bilotta and the rbot development team - https://ruby-rbot.org). I am imdb antz and its results show.

**Comment by mattzque** [comment]
Some regex changed for the title, I fixed that, but there is more broken, like it doesn't show genre or directors anymore. So I will need to work on this a bit more still.

**Comment by antdude** [comment]
Thanks again. It works. :)
