### ISSUE TITLE
Make rbot development active again. 

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#62]
;)

**Comment by Oblomov** [comment]
Be the change you want to see in the world ;-)

**Comment by Oblomov** [comment]
I think we've been pretty active these days 8-P

**Comment by antdude** [comment]
Welcome back. Where did you guys go? ;)

**Comment by Oblomov** [comment]
Work 8-D

**Comment by Oblomov** [comment]
Still work, but the freenode -> libera transition brought some of us back for some time.

**Comment by antdude** [comment]
It's quiet again. :P BTW, I had to quit my job since I wasn't getting paid. :(
