### ISSUE TITLE
Unable to git clone rbot!

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#87]
https://ruby-rbot.github.io/#Install says to use "git clone git://github.com/ruby-rbot/rbot.git", but it hangs for a few minutes:

$ git clone git://github.com/ruby-rbot/rbot.git
Cloning into 'rbot'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection timed out

In both updated Debian bookworm stable and Fedora release 39. :(

**Comment by jsn** [comment]
That should now be "https://" instead of "git://". I changed the web page.

**Comment by antdude** [comment]
Thanks.
